spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dh_login
    username: root
    password: wsymt1203
    druid:
      # 配置测试查询语句
      validationQuery: SELECT 1 FROM DUAL
      # 初始化大小，最小，最大
      initialSize: 10
      minIdle: 10
      maxActive: 200
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 180000
      testOnBorrow: false
      testWhileIdle: true
      removeAbandoned: true
      removeAbandonedTimeout: 1800
      logAbandoned: true
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxOpenPreparedStatements: 100
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j2
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  mail:
    host: smtp.163.com
    password: YTXBXOWTLHRQJZDL
    username: dhxtdatacenter@163.com

  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: HTML5
    cache: false



  redis:
    database: 0
    host: localhost
    port: 6379
    pool:
      max-active: 200
      max-wait: -1
      max-idle: 10
      min-idle: 0m
    timeout: PT30M


  session:
    store-type: redis
    timeout: PT30M
  jta:
    atomikos:
      connectionfactory:
        max-idle-time:


mybatis-plus:
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: com.wang.dhxt.common.domain.po
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
    cache-enabled: true
  global-config:
    db-config:
      logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0
logging:
  config: classpath:log4j2.xml
md5:
  key: feichangqiangdadekey

passwordChecker:
  #包含大写字母
  upperCase: true
  #包含小写字母
  lowerCase: true
  #包含字母
  letter: true
  #包含数字
  digit: true
  #包含特殊字符
  special: true
  #最小长度
  minLength: 8
  #最大长度
  maxLength: 20
